/**
 * The interviewer personas a series can be given. Each OpenAI Realtime voice
 * ships with a fixed name and character blurb — picking the voice picks the
 * name, so a male voice can never end up being called "Anna".
 *
 * Client-safe on purpose: the wizard's picker, the API's zod validation, and
 * the prompt builder all read from this one list. No server imports here.
 *
 * `marin`/"Anna" is the default and MUST stay so — every series created before
 * the voice column existed reads back as marin, and renaming their interviewer
 * mid-series would be a bug, not a feature.
 */
export type VoiceId = "marin" | "cedar" | "sage" | "coral" | "echo" | "alloy";

export type VoicePersona = {
  /** OpenAI Realtime voice id — passed straight through to the session config. */
  id: VoiceId;
  /** The interviewer's name. Interpolated into the system prompt and the UI. */
  name: string;
  /** One line of character, shown under the name in the picker. */
  blurb: string;
  /** Static sample clip, generated by scripts/generate-voice-samples.ts. */
  sample: string;
};

export const VOICES: VoicePersona[] = [
  { id: "marin", name: "Anna", blurb: "Warm and unhurried. Lets a silence sit.", sample: "/voices/marin.mp3" },
  { id: "cedar", name: "Ellis", blurb: "Dry and curious. Asks the question you were avoiding.", sample: "/voices/cedar.mp3" },
  { id: "sage", name: "Nora", blurb: "Calm and precise. Good with hard subjects.", sample: "/voices/sage.mp3" },
  { id: "coral", name: "Vivian", blurb: "Bright and quick. Keeps a conversation moving.", sample: "/voices/coral.mp3" },
  { id: "echo", name: "Gil", blurb: "Steady and plain-spoken. No performance.", sample: "/voices/echo.mp3" },
  { id: "alloy", name: "Reese", blurb: "Neutral and easy. Gets out of the way.", sample: "/voices/alloy.mp3" },
];

export const DEFAULT_VOICE: VoiceId = "marin";
export const DEFAULT_INTERVIEWER_NAME = "Anna";

/** Tuple form for `z.enum(VOICE_IDS)` — zod needs a non-empty literal tuple. */
export const VOICE_IDS = VOICES.map((v) => v.id) as [VoiceId, ...VoiceId[]];

/**
 * Resolve a stored voice id back to its persona. Falls back to the default
 * rather than throwing: a series row could carry a voice we've since retired,
 * and a retired voice should degrade to Anna, not 500 an interview.
 */
export function personaFor(id: string): VoicePersona {
  return VOICES.find((v) => v.id === id) ?? VOICES.find((v) => v.id === DEFAULT_VOICE)!;
}
