import type { Metadata } from "next";

/**
 * Every icon the site declares, in one place.
 *
 * Two Next behaviors collide here and are easy to get wrong:
 *
 *  - `app/favicon.ico` is emitted automatically, always. Listing it here too
 *    just produces a duplicate <link>, so it is deliberately absent.
 *  - Declaring `icons` at all switches OFF the file-convention pickup of
 *    `app/icon.svg`. The file still gets served, it just stops being linked —
 *    a silent regression a build will never catch. Hence the explicit entry.
 *
 * Browsers that understand the SVG prefer it (crisp at any size); the .ico
 * (16/32/48) is the fallback. iOS reads the apple-touch-icon and ignores the
 * manifest's icons entirely.
 *
 * All three are generated by `scripts/generate-pwa-assets.mjs`.
 */
export const ICONS: Metadata["icons"] = {
  icon: [{ url: "/icon.svg", type: "image/svg+xml" }],
  apple: "/apple-touch-icon.png",
};
